export default {
  SET_CUR_TEMPLATE: 'SET_CUR_TEMPLATE',
  SET_TEMPLATE_PROPERTY: 'SET_TEMPLATE_PROPERTY',
  SET_ANIMATION_VIEW_SIZE: 'SET_ANIMATION_VIEW_SIZE',
  SET_PAUSED: 'SET_PAUSED',
  ADD_NEW_LAYER: 'ADD_NEW_LAYER',
  SET_CUR_LAYER: 'SET_CUR_LAYER',
  DELETE_LAYER: 'DELETE_LAYER',
};
